name: Check
on: push
jobs: 
    testing:
        runs-on: macos-latest
        steps: 
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install deps
              run: npm ci
            - name: Testing
              run: npm run test

            